// Application-specific schema (non-auth tables go here)
// Auth tables are defined in auth.schema.ts (generated by Better Auth)

// Re-export auth schema for convenience
export { user as users } from './auth.schema';
